---

- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks: 

  - name: Updating the repository
    yum:
      update_cache: true

- hosts: controller_node 
  become: true
  roles:
    - network
    - ntp
    - packages
    - database 
    - message_queue 
    - memcached 
    - etcd

